version: '3'

services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=W@c[3~DV>~:]4%+5
      - POSTGRES_USER=jericho
      - POSTGRES_db=jericho
    ports:
      - "5432:5432"
  jericho:
    image: jericho-demo
    build:
      context: ./
      dockerfile: Dockerfile-Debug.dockerfile
    ports:
      - "5005:5005"
      - "8080:8080"
    volumes:
      - "~/.gradle:/home/gradle/.gradle"
    entrypoint:
      - gradle
      - run
      - --debug-jvm
      - --no-daemon
    depends_on:
      - database