version: '3'

services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=W@c[3~DV>~:]4%+5
      - POSTGRES_USER=jericho
      - POSTGRES_db=jericho
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "~/tmp/jericho-pgsql-release:/var/lib/postgresql/data"
    networks:
      - ICNDB-Net
  icndb:
    image: baez90/jericho-victim:latest
    environment:
      - "JDBC_HOSTNAME=database"
      - "JDBC_USER=jericho"
      - "JDBC_PASSWORD=W@c[3~DV>~:]4%+5"
      - "VERTICLES_COUNT=4"
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - ICNDB-Net
      - JerichoBattlefield
networks:
  ICNDB-Net:
  JerichoBattlefield:
    driver: bridge
