version: '3.4'

services:
  gatling-attacker:
    image: baez90/jericho-attacker:2.3.0
    volumes:
      - type: volume
        source: gatling-logs
        target: /opt/gatling/shared-results
    configs:
      - source: RandomJokeSimulation
        target: /opt/gatling/user-files/simulations/RandomJokeSimulation.scala
    networks:
      - JerichoBattlefield
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
  gatling-reporter:
    image: baez90/jericho-reporter:2.3.0
    volumes:
      - type: volume
        source: gatling-logs
        target: /opt/gatling/results
      - type: volume
        source: gatling-results
        target: /opt/gatling/html-out
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
  report-viewer:
    image: nginx:1.13-alpine
    ports:
      - target: 80
        published: 50080
        protocol: tcp
        mode: ingress
    volumes:
      - type: volume
        source: gatling-results
        target: /usr/share/nginx/html
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s

networks:
  JerichoBattlefield:
    external:
      name: JerichoBattlefield

volumes:
  gatling-logs:
    driver: nfs
    driver_opts:
      share: 192.168.111.30:/var/nfs/gatling-logs
  gatling-results:
    driver: nfs
    driver_opts:
      share: 192.168.111.30:/var/nfs/gatling-results

configs:
  RandomJokeSimulation:
    external: true