version: '3.4'

services:
  gatling-attacker:
    image: baez90/jericho-attacker:2.3.0
    volumes:
      - type: volume
        source: gatling-logs
        target: /opt/gatling/shared-results
      - type: volume
        source: ${PWD}/MachineGuns/RandomJokeSimulation.scala
        target: /opt/gatling/user-files/simulations/RandomJokeSimulation.scala
        read_only: true
    networks:
      - JerichoBattlefield
  gatling-reporter:
    image: baez90/jericho-reporter:2.3.0
    volumes:
      - type: volume
        source: gatling-logs
        target: /opt/gatling/results
      - type: volume
        source: gatling-results
        target: /opt/gatling/html-out
  report-viewer:
    image: nginx:1.13-alpine
    ports:
      - "50080:80"
    volumes:
      - type: volume
        source: gatling-results
        target: /usr/share/nginx/html

networks:
  JerichoBattlefield:
    external:
      name: sajericho_JerichoBattlefield

volumes:
  gatling-logs:
  gatling-results: